import { Product } from "../../core/models/card-product-home";

export const cardsData: Product[] = [
    {
        id: 1,
        image: "imagens-home/arara-campeao-250.avif",
        title: "Café Arara Campeão -",
        title_highlight: " 86,75 pts ",
        type: "Torrado e Moído",
        specification: "250g - 49,90",
        description: "Um café com notas de chocolate, panetone, brownie, baunilha e caramelo com toques cítricos, resultando em uma bebida equilibrada, doce e intensamente aromática. ",
        description_highlight: "Ideal para espresso e métodos filtrados.",

    },
    {
        id: 2,
        image: "imagens-home/arara-500g.avif",
        title: "Café Arara Campeão - ",
        title_highlight: "86,75 pts",
        type: "Torrado em Grãos",
        specification: "500g - 90,00",
        description: "Um café com notas de chocolate, panetone, brownie, baunilha e caramelo com toques cítricos, resultando em uma bebida equilibrada, doce e intensamente aromática.",
        description_highlight: "Versátil e marcante em espresso ou filtrados.",
    },
    {
        id: 3,
        image: "imagens-home/arara-campeao-250.avif",
        title: "Café Arara Campeão -",
        title_highlight: " 86,75 pts ",
        type: "Torrado em Grãos",
        specification: "500g - 90,00",
        description: "Um café com notas de chocolate, panetone, brownie, baunilha e caramelo com toques cítricos, resultando em uma bebida equilibrada, doce e intensamente aromática. ",
        description_highlight: "Ideal para espresso e métodos filtrados.",

    },
    {
        id: 4,
        image: "imagens-home/arara-500g.avif",
        title: "Café Arara Campeão - ",
        title_highlight: "86,75 pts",
        type: "Torrado e Moído",
        specification: "250g - 49,90",
        description: "Um café com notas de chocolate, panetone, brownie, baunilha e caramelo com toques cítricos, resultando em uma bebida equilibrada, doce e intensamente aromática.",
        description_highlight: "Versátil e marcante em espresso ou filtrados.",

    },
    {
        id: 5,
        image: "imagens-home/arara-moca.avif",
        title: "Arara Moca -",
        title_highlight: " 85 pts ",
        type: "Torrado em Grãos",
        specification: "250g - 44,90",
        description: "Um café elegante e equilibrado, com notas de chocolate, brownie, caramelo e frutas cítricas, envolvidas por um delicado aroma floral.",
        description_highlight: " Uma experiência refinada em cada preparo.",

    },
    {
        id: 6,
        image: "imagens-home/arara-moca-moido.avif",
        title: "Arara Moca -",
        title_highlight: " 85 pts",
        type: "Torrado e Moído",
        specification: "250g - 44,90",
        description: "Um café elegante e equilibrado, com notas de chocolate, brownie, caramelo e frutas cítricas, envolvidas por um delicado aroma floral.",
        description_highlight: " Uma experiência refinada em cada preparo.",

    }, {
        id: 7,
        image: "imagens-home/geisha-nanolote.avif",
        title: "Geisha Nanolote - ",
        title_highlight: "86 pts",
        type: "Torrado e Moído",
        specification: "250g - R$49,90",
        description: "Nanolote Edição Especial do Projeto Mine Lab: um blend experimental das variedades Arara, Paraíso 2, Catiguá e Geisha, cultivado em sistema de cafeicultura regenerativa, que entrega uma ",
        description_highlight: "bebida limpa, doce e suave, com acidez leve, equilíbrio refinado e um corpo macio e envolvente.",
    },
    {
        id: 8,
        image: "imagens-home/geisha-nanolote-grao.avif",
        title: "Geisha Nanolote - ",
        title_highlight: "86 pts",
        type: "Torrado em Grãos",
        specification: "250g - R$49,90",
        description: "Nanolote Edição Especial do Projeto Mine Lab: um encontro experimental entre Arara, Paraíso 2, Catiguá e Geisha, cultivados sob princípios de cafeicultura regenerativa, revelando uma ",
        description_highlight: "bebida limpa e delicada, com doçura natural, acidez suave e um corpo macio, denso e perfeitamente equilibrado.",
    }, {
        id: 9,
        image: "imagens-home/chocomilk.avif",
        title: "Chocomilk - ",
        title_highlight: "85 pts",
        type: "Torrado e Moído",
        specification: "250g - R$44,90",
        description: "Notas marcantes de chocolate ao leite, caramelo e açúcar mascavo, resultando em uma ",
        description_highlight: "bebida de alta doçura, com corpo cremoso e final envolvente. ",
    }, {
        id: 10,
        image: "imagens-home/chocomilk.avif",
        title: "Chocomilk - ",
        title_highlight: "85 pts",
        type: "Torrado em Grãos",
        specification: "250g - R$44,90",
        description: "Uma combinação indulgente de chocolate ao leite, caramelo e açúcar mascavo, que entrega ",
        description_highlight: "alta doçura, corpo cremoso e uma finalização suave e reconfortante.",
    }, {
        id: 11,
        image: "imagens-home/chocomilk-500g.avif",
        title: "Chocomilk - ",
        title_highlight: "85 pts",
        type: "Torrado e Moído",
        specification: "500g - 80,00",
        description: "Notas marcantes de chocolate ao leite, caramelo e açúcar mascavo, resultando em uma ",
        description_highlight: "bebida de alta doçura, com corpo cremoso e final envolvente. ",
    },{
        id: 12,
        image: "imagens-home/chocomilk-500g.avif",
        title: "Chocomilk - ",
        title_highlight: "85 pts",
        type: "Torrado em Grãos",
        specification: "500g - 80,00",
        description: "Uma combinação indulgente de chocolate ao leite, caramelo e açúcar mascavo, que entrega ",
        description_highlight: "alta doçura, corpo cremoso e uma finalização suave e reconfortante.",
    }, {
        id: 13,
        image: "imagens-home/fruit-catucai.avif",
        title: "Fruit Catucaí 2SL",
        title_highlight: "Torrado em Grãos",
        type: "",
        specification: "250g - 44,90",
        description: "Um café com doçura equilibrada, que combina notas de caramelo e doce de leite com o frescor de frutas maduras. ",
        description_highlight: "Um sabor marcante para quem valoriza qualidade em cada preparo.",

    },
    {
        id: 14,
        image: "imagens-home/fruit-catucai-moido.avif",
        title: "Fruit Catucaí 2SL",
        title_highlight: "Torrado e Moído",
        type: "",
        specification: "250g - 44,90",
        description: "Um café com doçura equilibrada, que combina notas de caramelo e doce de leite com o frescor de frutas maduras. ",
        description_highlight: "Um sabor marcante para quem valoriza qualidade em cada preparo.",

    }, {
        id: 15,
        image: "imagens-home/arara-lata.avif",
        title: "Café Arara Campeão -",
        title_highlight: " 86,75 pts",
        type: "torrado em Grãos, Tubolata",
        specification: "250g - R$55,00",
        description: "Notas de chocolate, panetone, brownie, baunilha, caramelo e frutas cítricas. Bebida equilibrada, adocicada e aromática. ",
        description_highlight: "Embalagem premium, ideal para presentes e revenda.",

    },
    {
        id: 16,
        image: "imagens-home/dripp-coffee.avif",
        title: "Dripp Coffee -",
        title_highlight: " Praticidade ",
        type: "Torrado e Moído",
        specification: "Caixa com 10 sachês - R$39,90",
        description: "Café que unem praticidade e sabor, com notas de chocolate ao leite, frutas cítricas e baunilha, proporcionando uma experiência equilibrada e aromática ",
        description_highlight: "É só adicionar água quente e aproveitar."

    },

]